### ISSUE TITLE
Extract pdb receptor file from database 

### ISSUE THREAD

**Issue by agusgrich** [forlilab/Ringtail#11]
Hello  good morning, 

I am traying to export de pdb receptor file from the database. I already saved the pdbqt receptor file in the database,  and when I have the results of my studies I want to see the pdb ligands files  with the pdb receptor file but I only could extract the pdb ligands files. 
I could not find an argument to extract this information from the database. Is there an argument to extract this? 

Thank you in advance for the support,

kind regards.

Agus.

**Comment by althea-hansel** [comment]
Hi Agus,

Thank you for using Ringtail! There is not currently an option to re-export a receptor file. We hope to be releasing a v1.1 shortly and can include an option for this in that release.

**Comment by althea-hansel** [comment]
Hello Agus,

The `--export_receptor` option has now been added in the `GUI` branch. Please note that this branch is still under development and may have bugs we have not found yet. You will need to install Ringtail from the source code while on the `GUI` branch, if you have not already done so. Please let me know if you have any other issues or questions. Thank you for this suggestion!
