### ISSUE TITLE
Sdf writing features

### ISSUE THREAD

**Issue by mattholc** [forlilab/Ringtail#24]
Right now when you write out sdfs each mol is written to its own sdf, with its name as the filename. Two modifications would aid in rescreening:

1) all mols should be written to a single sdf, consistent with the expectations of meeko for preparing pdbqts, and reducing number of files
2) regardless of above, the name of the molecule should be included in the sdf, so that if they are read by rdkit the molecule retains its name

**Comment by maylinnp** [comment]
@mattholc would the expectation be to always write one large file of SDFs, or do you see a reason to make it an option to write one SDF per molecule or multiple molecules in one SDF?

**Comment by diogomart** [comment]
Just to have in writing what me and @mattholc discussed: single SDF is strongly preferred, reason to have them split was so that pymol loads each pose as a different object; script will be written if needed to split

**Comment by maylinnp** [comment]
Added ability to write all molecules in a bookmark (or database) to a single SDF. Default option will write one SDF per molecule.
3c79d92
