### ISSUE TITLE
Ligand interaction export option

### ISSUE THREAD

**Issue by althea-hansel** [forlilab/Ringtail#25]
Add option for exporting the ligand interactions for a given bookmark. Maybe as CSV?

**Comment by maylinnp** [comment]
@althea-hansel Are you thinking that for ligands that passed a filter and are in a bookmark (that does not contain interaction data) to produce a csv containing each ligand/pose_id and only interaction data, e.g.:

ligand,pose_id,interaction_type,interaction
12ab3d,1,H,A:LYS:162
12ab3d,5,V,A:VAL:279
4e56fg,3,V,A:LYS:162

**Comment by maylinnp** [comment]
It is possible to export a csv file by writing a custom sqlite query, either using the Ringtail command line tool or directly through the API.

Below are examples of a query that gets ligand name, docking score, and some interaction information for ligands passing a filter, assuming a database 'output.db' with a bookmark 'passing_results' with desired filtered data:

API
`rtc = RingtailCore("output.db")`
`rtc.export_csv(
    """SELECT r.LigName, r.docking_score, i.interaction_type, i.rec_resname, i.rec_resid FROM Results r 
    JOIN Interactions i ON r.Pose_ID = i.Pose_ID WHERE i.Pose_ID IN (SELECT Pose_ID FROM passing_results)""",
    "interactions.csv",
)`

cmd line:
`python ../scripts/rt_process_vs.py read --input_db output.db --export_query_csv 'SELECT r.LigName, r.docking_score, i.interaction_type, i.rec_resname, i.rec_resid FROM Results r JOIN Interactions i ON r.Pose_ID = i.Pose_ID WHERE i.Pose_ID IN (SELECT Pose_ID FROM passing_results)' "`
