### ISSUE TITLE
Clustering on an existing bookmark doesn't do anything

### ISSUE THREAD

**Issue by mattholc** [forlilab/Ringtail#27]
I created a bookmark and then tried to run morgan fingerprint clustering on it, and it immediately closed the database instead of performing the clustering. Code posted below.

rt_process_vs.py read -i input.db -pe 1 -hb B:ASP:534: -hb B:Ser:699: -l step1.log -s step1
rt_process_vs.py read -i input.db -mfpc -fb step1 -l step2.log -s step2

**Comment by maylinnp** [comment]
This issue has been fixed in ringtail 2.0.0
