### ISSUE TITLE
Error occurred while writing SDF from RDKit Mol

### ISSUE THREAD

**Issue by LeThucMinhChau** [forlilab/Ringtail#28]
I try to write SDF file from my bookmark, however, I tried to export SDF files but it returns: 'Error occurred while writing SDF from RDKit Mol'. I am using the new version of Ringtail, is there any updates in the dependencies or is it a bug in the code? 

rt_process_vs.py read -i input.db -s bookmark --export_sdf_path sdf

**Comment by althea-hansel** [comment]
Hi, thank you for reaching out! There is an additional dependency on `chemicalite` which is frequently the issue, in case you have not installed that yet.

If that does not resolve the issue, can you please run `rt_process_vs.py read -i input.db -s bookmark --export_sdf_path sdf -d` and share the output?

**Comment by sribone** [comment]
I have the same problem! I already update chemicalite, but the error persist. The -d option is returning the following message:

Logging level set to debug
Writing SR13.sdf
Closing database
Traceback (most recent call last):
  File "/home/sribone/anaconda3/envs/ringtail/lib/python3.10/site-packages/ringtail/outputmanager.py", line 210, in write_out_mol
    mol = RDKitMolCreate.combine_rdkit_mols(mol_flexres_list)
  File "/home/sribone/anaconda3/envs/ringtail/lib/python3.10/site-packages/meeko/rdkit_mol_create.py", line 370, in combine_rdkit_mols
    data = json.loads(mol.GetProp("meeko"))
KeyError: 'meeko'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sribone/anaconda3/envs/ringtail/bin/rt_process_vs.py", line 86, in <module>
    rt_core.write_molecule_sdfs()
  File "/home/sribone/anaconda3/envs/ringtail/lib/python3.10/site-packages/ringtail/ringtailcore.py", line 465, in write_molecule_sdfs
    self.output_manager.write_out_mol(
  File "/home/sribone/anaconda3/envs/ringtail/lib/python3.10/site-packages/ringtail/outputmanager.py", line 224, in write_out_mol
    raise OutputError("Error occurred while writing SDF from RDKit Mol") from e
ringtail.exceptions.OutputError: Error occurred while writing SDF from RDKit Mol

ERROR: Error occurred while writing SDF from RDKit Mol

**Comment by althea-hansel** [comment]
Thank you for including the error traceback. Can you please check what version of Meeko you have installed?

**Comment by althea-hansel** [comment]
Thank you very much. I was able to reproduce your error with the latest version of Meeko but not an older one. I have escalated this issue to the senior Meeko developer and we will keep you updated on the progress.

**Comment by diogomart** [comment]
Fixed in https://github.com/forlilab/Meeko/commit/9e8a7ad679fb0577a2107e2d5c6dd8192e4198db. We are releasing meeko v0.6.0 soon and it will include this fix.

**Comment by diogomart** [comment]
Fixed in Meeko v0.6.0-alpha.3
