### ISSUE TITLE
Filters -mfpc -ifpc do not pass any ligands

### ISSUE THREAD

**Issue by LeThucMinhChau** [forlilab/Ringtail#30]
Hi Althea and team,

I used -mfpc and -ifpc with the last version of Ringtail (v1.0.0), I was able to apply both filters with warning that the interaction filter would be applied first and then morgan fingerprint (I remembered). However, recently, I tried to used them again but those filters does not work, as when I entered the filters there is no results return. 

![image](https://github.com/forlilab/Ringtail/assets/117782954/ddacdb74-d66f-4a77-8caa-a446d3f7914b)
![image](https://github.com/forlilab/Ringtail/assets/117782954/13566954-1fca-4d98-accb-1234e86a9d39)

Here, usually if there is a result pass through the screen will provide the number of ligands passed the filter, here's not. Even, when I open the database, I cannot find the bookmark. 

Can I have your help upon this point? 
Thank you very much!

**Comment by maylinnp** [comment]
I believe this issue has been fixed in ringtail 2.0.0 (see comment on issue provided by matt)
