### ISSUE TITLE
Feature request: Modules for AUC, BEDROC and EF 

### ISSUE THREAD

**Issue by eunos-1128** [forlilab/Ringtail#37]
Hi,

It seems to lack functions for calculating and plotting AUC, BEDROC and EF after virtual screening.

Any plan to implement them? 

Regards,

**Comment by rwxayheee** [comment]
Hi @eunos-1128 

> It seems to lack functions for calculating and plotting AUC, BEDROC and EF after virtual screening.

There are [some examples in README](https://github.com/forlilab/Ringtail?tab=readme-ov-file#make-an-roc-plot-and-calculate-its-auc-for-a-virtual-screening-with-a-file-containing-a-list-of-known-binders). I am also learning to use it and need to take a closer look, though. Were you able to generate a plot following this example? For `lack of functions`, do you mean lack of dependencies (`sklearn`)?

**Comment by eunos-1128** [comment]
@rwxayheee 

>  There are [some examples in README](https://github.com/forlilab/Ringtail?tab=readme-ov-file#make-an-roc-plot-and-calculate-its-auc-for-a-virtual-screening-with-a-file-containing-a-list-of-known-binders). 

I've known the examples. 

>  For lack of functions, do you mean lack of dependencies (sklearn)?

No, I meant useful and concise functions like commands

Otherwise, RDkit has some useful [Python API](https://www.rdkit.org/docs/source/rdkit.ML.Scoring.Scoring.html) for virtual screening metrics.
People can use them to calculate metrics and make plots.

I think that it would be incredibly convenient if, by simply inputting a command with additional options using the docking results from a database, automatic calculations of AUC, BEDROC, and EF could be performed, followed by the generation of plots.

**Comment by diogomart** [comment]
The results have to be labeled for calculating those metrics. In ringtail, that would require an extra column in a table, and additional user input to label each entry. I think that brings more complexity than benefits and should not be implemented.

**Comment by diogomart** [comment]
I'm closing this issue, as there is no plan to implement these features, but feel free to continue the discussion.

**Comment by eunos-1128** [comment]
@diogomart 

I understand what you meant to. Thank you for explaining.
