### ISSUE TITLE
Check if bookmark exists before `RingtailCore.write_molecule_sdfs`

### ISSUE THREAD

**Issue by rwxayheee** [forlilab/Ringtail#40]
When conditions in `rtc.filter` result in 0 ligands passing the **first?** filter, no view (bookmark) will be created. 

`rtc.write_molecule_sdfs` is still callable, with the following error:  
`UnboundLocalError: cannot access local variable 'all_mols' where it is not associated with a value`

This is more of a "view isn't created" problem. It seemed to only occur when the first filter applied returns 0 matched ligands. 

Not very sure what's the best way to guard this... Some other potentially useful functions like: 
[storageman.get_number_passing_ligands](https://github.com/forlilab/Ringtail/blob/2905f67606b3ddd3c3a623fe9759654d6762e281/ringtail/storagemanager.py#L1909)
also won't work when a view isn't created. **But it works fine when an existing view has 0 ligands.**

There isn't a check in `rt_process_vs.py` either. Same error with nonexistent bookmark: 
```
Traceback (most recent call last):
  File "/Users/amyhe/Downloads/Ringtail/scripts/rt_process_vs.py", line 70, in <module>
    rtcore.write_molecule_sdfs()
  File "/Users/amyhe/Downloads/Ringtail/ringtail/ringtailcore.py", line 1432, in write_molecule_sdfs
    all_mols = self.ligands_rdkit_mol(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/amyhe/Downloads/Ringtail/ringtail/ringtailcore.py", line 1509, in ligands_rdkit_mol
    return all_mols
           ^^^^^^^^
UnboundLocalError: cannot access local variable 'all_mols' where it is not associated with a value
```

**Comment by maylinnp** [comment]
This should be fixed now, I added checks for 
a) does bookmark exist and
b) does bookmark have data

before proceeding to gather filter data to use in sdfs writing in commit c6e586a.
