### ISSUE TITLE
Filters in pytest `test_similar_ligands_mfpt` and `test_similar_ligands_interaction` Failed on certain platforms

### ISSUE THREAD

**Issue by rwxayheee** [forlilab/Ringtail#42]
No issue on Mac. On Linux clusters (and maybe with certain versions/builds of other packages..), the two tests did not pass. 

log (stdout and stderr) for `pytest test_units.py`
[test_units.log](https://github.com/user-attachments/files/16140950/test_units.log)

`micromamba list`
[mamba_list.txt](https://github.com/user-attachments/files/16141000/mamba_list.txt)

`pip list`
[pip_list.txt](https://github.com/user-attachments/files/16141002/pip_list.txt)

The direct reason was that the filters returned 0 passing ligands and did not create a bookmark. I don't know the actual cause, but I will comment here if I figure out why it's not working on Linux

**Comment by maylinnp** [comment]
Fixed, old code defaulted to Python internal `multiprocessing` on Linux, which is not able to pickle the object involved in clustering. Ringtail now uses `multiprocess` exclusively, which can pickle more object.
[a793a2a](https://github.com/forlilab/Ringtail/commit/a793a2af619f1dae77a72e6783e269bef659f37b)
