### ISSUE TITLE
`too many columns on Interaction_bitvectors` when trying to write .db from docking outputs

### ISSUE THREAD

**Issue by rwxayheee** [forlilab/Ringtail#43]
[SQLite has a limit on the number of columns per table](http://www.sqlite.org/limits.html) (2000). This may be exceeded when the database contains docking results from multiple binding sites (different docking boxes). 

I encountered this problem when trying to write .db from some docking ouput files using `rt_process_vs.py write`. It's still possible to perform basic filtering with the same pool of docking files using API, as long as it's not writing the bitvectors into columns:  

```
Total Stored Ligands          : 153
Total Stored Poses            : 97920
Total Unique Interactions     : 2064
Number Interacting Residues   : 486

Energy statistics:
=======================================
Energy (min)      : -12.13 kcal/mol
Energy (max)      : -0.79 kcal/mol
LE     (min)      : -0.36 kcal/mol/heavyatom
LE     (max)      : -0.02 kcal/mol/heavyatom
----------------------------------------
Energy (top 1% )  : -11.13 kcal/mol
Energy (top 10% ) : -9.67 kcal/mol
LE     (top 1% )  : -0.36 kcal/mol/heavyatom
LE     (top 10% ) : -0.30 kcal/mol/heavyatom
```

(to avoid exceeding `SQLITE_MAX_COLUMN`, some compression/transformation of bitvectors might help, but we can also advise users to not put results from different boxes into the same pool like this. Still, it's very possible to exceed the max. number of columns in flexible residue docking, or pooling results from blind docking

Some changes in how interactions are stored might be helpful for merging db from different ADGPU docking runs. Currently, the number of columns depend on docking results

**Comment by maylinnp** [comment]
Very good observation! I have tried a different version of handling interaction data (in an earlier commit), it could be a bit slower to run but implementing it would be fast (and it should solve your issue). I will keep this issue open and we will discuss it in a future ringtail meeting.

**Comment by sforli** [comment]
Maybe interactions could be stored in a separate table as rows, and in the ligand pose table we can store only the reference to the interactions.

However, I'm not sure if it's possible to generate such a large bit vector, if interactions are so many/large.



--
Stefano Forli, PhD

Associate Professor
Dept. of Integrative Structural
and Computational Biology, MB-112A
Scripps Research
10550 North Torrey Pines Road
La Jolla, CA 92037-1000, USA.

tel: +1 (858)784-2055<tel:+18587842055>
email: ***@***.******@***.***>
https://forlilab.org<https://forlilab.org/>
________________________________

**Comment by maylinnp** [comment]
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Aptos;
	panose-1:2 11 0 4 2 2 2 2 2 4;}
@font-face
	{font-family:"Times New Roman \(Body CS\)";
	panose-1:2 11 6 4 2 2 2 2 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:12.0pt;
	font-family:"Aptos",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
span.EmailStyle19
	{mso-style-type:personal-reply;
	font-family:"Arial",sans-serif;
	color:windowtext;}
.MsoChpDefault
	{mso-style-type:export-only;
	font-size:10.0pt;
	mso-ligatures:none;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by rwxayheee** [comment]
Thank you all for your kind replies. Handling interactions as bitvectors is fine, but the column-based bit vector table doesn't have a constant number of columns (or can have too many columns). This makes merging tables from different docking runs impossible. A tree-type data structure might be more compact than directly expanding the bitvectors as columns, and can be stored in a single column. But I don't know if it's efficient performance wise. 
I use a different interaction comparison method (and I'm sure May-Linn has better ones too) but right now I don't have much time to implement it for Ringtail. We can discuss more when we get a chance

**Comment by maylinnp** [comment]
We discussed this issue during a group meeting and found this is only an issue when docking with > 3 flexible side chains. We will work on a future feature release for Ringtail dealing with this kind of docking.
