### ISSUE TITLE
Raise error, exit, or return 0 poses, instead of automatically ignoring interaction that doesn't exist

### ISSUE THREAD

**Issue by diogomart** [forlilab/Ringtail#49]
I think that automatically ignoring an interaction is not user-friendly. My case: filtered for an interaction but had a typo, and that interaction was automatically dropped. It was a large .db and the subsequent filtering took minutes. Ctrl+C still takes some time to be caught. It's better to just exit and allow the user to fix the typo. Alternatively, returning 0 poses and warning the user about non-existing interaction is also OK.

**Comment by maylinnp** [comment]
Fixed in commit 6dc383a on `api_dev`. Where it would previously write a warning in the log, it will now raise an exception stating interaction is not in the database, and check for misspelling or remove from filter.
