### ISSUE TITLE
Molecule name missing

### ISSUE THREAD

**Issue by diogomart** [forlilab/Ringtail#50]
Originally reported in #24, the molecule name should be included as a property of the RDKit molecule, for example `rdkit_mol.setProp("_Name", "best_molecule_ever")`, and this name will automatically appear in the first line of the SDF files.

**Comment by maylinnp** [comment]
My bad! I added this feature in the `interaction_tables_indexed` branch commit 05957da, and will mark this issue as resolved once the branch is merged back with `api_dev`.

**Comment by diogomart** [comment]
I don't think it's working yet, could you check?

**Comment by diogomart** [comment]
Nevermind, it is adding the name. But for N passing molecules, I got an SDF with N+1 molecules, and the first one didn't have a name.

**Comment by diogomart** [comment]
Nevermind x2, the SDWriter is in append mode, and the first molecule was from a prior run before the fix. All is good :)

**Comment by maylinnp** [comment]
fixed in commit 05957da on the `develop` branch
