### ISSUE TITLE
Optionally export PDB with docked sidechains and a full copy of the rest of the receptor instead of with the ligand SDF

### ISSUE THREAD

**Issue by diogomart** [forlilab/Ringtail#55]

**Comment by maylinnp** [comment]
Does this mean docked -flexible- sidechains? 
And does this issue have any relation to issue [parse and use INDEX_MAP for flexible sidechains #60](https://github.com/forlilab/Ringtail/issues/60)?

**Comment by diogomart** [comment]
Yes, docked positions for flexible sidechains.

Yes, #60 basically supersedes this issue, it describes what needs to be implemented. I'll close here, let's continue on #60
