### ISSUE TITLE
Add dependencies to setup.py, or requirements.txt, or similar, if chemicalite is dropped or becomes available from PyPI

### ISSUE THREAD

**Issue by diogomart** [forlilab/Ringtail#58]
The idea is to have a pip install from PyPI install all dependencies, but that is currently impossible because chemicalite is available only from conda-forge.

**Comment by rwxayheee** [comment]
The dependencies are not entirely clear from README, we might want to require: 

pandas 

matplotlib (& ipykernel)

multiprocess (not just for MacOS, this is required on Google Linux backends)

**Comment by maylinnp** [comment]
Updated dependencies in readme (79b6b6e), working on a forked version without chemicalite where all dependencies are now installed using the pyproject.toml.
Will wait to close this issue until that version is released.

**Comment by diogomart** [comment]
Opening this issue might have been a bad idea... sorry. @nbruciaferri recently said the current most popular practice is to have **_no_** dependencies listed for PyPI installation, and I think that would include pyproject.toml, and list dependencies only on the conda-forge recipe. This prevents pip from checking and enforcing dependencies and delegates all dependency management to a snake-named package manager, which are recognized to be better at package managing that pip.

**Comment by diogomart** [comment]
Just PR'ed removal of dependencies from `setup.py` in meeko: https://github.com/forlilab/Meeko/pull/274

**Comment by maylinnp** [comment]
Gotcha, I will close this issue then. Ringtail currently does not have dependencies/requirements in setup.py, I just added it in my personal dev branch so I'll keep the pyproject.toml for a future release but remove the dependencies.
