### ISSUE TITLE
Logical operator between groups of conditions and within a group

### ISSUE THREAD

**Issue by rwxayheee** [forlilab/Ringtail#62]
Hi @maylinnp 

I asked about this earlier today. I was following [the API procedure](https://ringtail.readthedocs.io/en/stable/api.html#ligand-filters) in the documentation. I see that the `ligand_operator` option in `rtc.filter` may control the evaluation of multiple conditions in `ligand_substruct`. 

[here](https://github.com/forlilab/Ringtail/blob/release/ringtail/storagemanager.py#L3176) I see that the same operator is also used between filtering conditions. 

There might be a small problem when different types of filtering conditions are present: it seems like the operator between the last "ligand_name" condition and the next condition is always OR, and the operator between "ligand_max_atoms" and the next condition is the `ligand_operator`. 

If `ligand_operator` is only used by (both) `ligand_substruct` and `ligand_substruct_pos`, you might want the logical operator between different types of filtering conditions to be AND. It might be helpful to introduce parentheses to group conditions and achieve the desired order of evaluation.

**Comment by maylinnp** [comment]
Yes, this is exactly the bug I was referring to earlier. I had not elucidated just in how many places it was an issue so thank you for highlighting some of the areas it was a problem that I had not noticed yet. I will work on a bug fix and hopefully have it ready by next week.

**Comment by maylinnp** [comment]
Fixed in commit 83e2fa8, will be in the next release.
