### ISSUE TITLE
Possible problems with the overwrite and add_interactions options

### ISSUE THREAD

**Issue by xavgit** [forlilab/Ringtail#65]
Hi,
I have the results of about 10000 drugs docked with adgpu.
For the overwrite problem.
To construct the DB I've used the following command having in the working directory the database previously made named c1_adgpu_ad4_sf.db:

rt_process_vs write --debug  --output_db c1_adgpu_ad4_sf.db --file_path ../docking_results --store_all_poses --receptor_file ../receptor.pdbqt --save_receptor --add_interactions --overwrite | tee command_debug_output.txt

With  this command I receive many Errors.
[command_debug_output.txt](https://github.com/user-attachments/files/17991700/command_debug_output.txt)
[ringtail_failed_files_with_overwrite.log](https://github.com/user-attachments/files/17991701/ringtail_failed_files_with_overwrite.log)

Without the overwrite option and having deleted the existing database I do not receive errors.
[20241203-115258_ringtail.log](https://github.com/user-attachments/files/17991724/20241203-115258_ringtail.log)
[command_debug_output_without_overwrite.txt](https://github.com/user-attachments/files/17991727/command_debug_output_without_overwrite.txt)

I'm using the overwrite option in a wrong way?

For the add_interactions.
If I run the following: 
$ rt_process_vs read --verbose --input_db c1_adgpu_ad4_sf.db --print_summary 
/home/xxxx/.local/lib/python3.10/site-packages/Bio/pairwise2.py:278: BiopythonDeprecationWarning: Bio.pairwise2 has been deprecated, and we intend to remove it in a future release of Biopython. As an alternative, please consider using Bio.Align.PairwiseAligner as a replacement, and contact the Biopython developers if you still need the Bio.pairwise2 module.
  warnings.warn(
INFO - ringtailcore.py:64 - [     New RingtailCore object initialized with database file c1_adgpu_ad4_sf.db    ]
INFO - ringtailoptions.py:120 - A StorageOptions object was created with default values for all attributes.
INFO - ringtailcore.py:752 - Options for storage manager have been changed.
INFO - cloptionparser.py:708 - Command line prompt: ['/home/xxxx/.local/bin/rt_process_vs', 'read', '--verbose', '--input_db', 'c1_adgpu_ad4_sf.db', '--print_summary']
INFO - ringtailoptions.py:120 - A OutputOptions object was created with default values for all attributes.
INFO - ringtailcore.py:855 - Options for output manager have been changed.
INFO - ringtailcore.py:752 - Options for storage manager have been changed.
INFO - storagemanager.py:3237 - Ringtail connected to database c1_adgpu_ad4_sf.db.
INFO - storagemanager.py:3510 - Closing database
Total Stored Ligands          : 9705
Total Stored Poses            : 1242240
Total Unique Interactions     : 0
Number Interacting Residues   : 0

Energy statistics:
\=======================================
Energy (min)      : -24.49 kcal/mol
Energy (max)      : 1.68 kcal/mol
LE     (min)      : -5.13 kcal/mol/heavyatom
LE     (max)      : 0.05 kcal/mol/heavyatom
\----------------------------------------
Energy (top 1% )  : -12.58 kcal/mol
Energy (top 10% ) : -10.27 kcal/mol
LE     (top 1% )  : -0.58 kcal/mol/heavyatom
LE     (top 10% ) : -0.33 kcal/mol/heavyatom
INFO - rt_process_vs.py:101 - Time to initialize/write database: 0.01 seconds
INFO - rt_process_vs.py:106 - Time to perform filtering: 1.08 seconds 
..........................................................................................................................................................................

Why I receive the following?
Total Unique Interactions     : 0
Number Interacting Residues   : 0

The only thing I've noticed is that the receptor.pdbqt , derived from a .pdb returned from cpptraj as representative 
frame of a cluster , has not the chain ids.
The receptor is a complex of two proteins.

Any suggestions?

Thanks.

Saverio

**Comment by maylinnp** [comment]
Hi @xavgit , this definitely looks like bugs, you are using `--overwrite` as expected. 
Do you happen to have the `YYYYMMDD-hhmmss_ringtail.log` file for the first command line call you share as well?

**Comment by diogomart** [comment]
@xavgit just a slightly unrelated tip: option `-C 1` in adgpu triggers contact analysis (interactions) on, then you won't need `--add_interactions` in ringtail. Vina can't do this.

**Comment by xavgit** [comment]
Hi,
thanks to all.
For the log file I can rerun , in the same conditions , the command to post the returned log file.
For the adgpu -c 1 option I have not used it for the dockings of the six representative 
cluster frames therefore it can be useful to me having now such type of information.

Saverio

 
[20241204-190605_ringtail.log](https://github.com/user-attachments/files/18012469/20241204-190605_ringtail.log)

**Comment by maylinnp** [comment]
The bug was related to the `overwrite` option and I have a bug fix for it. I hope to push this with some other small bug fixes (and enhanced plot handling) for a release shortly.

Thank you also for your detailed issue reports, this makes it easy to straighten things out!
I will comment on and close your issues once the release is available.

**Comment by xavgit** [comment]
Hi,
Thanks.

Saverio

**Comment by maylinnp** [comment]
Fixed in commit 5cbf721, will be in next release.
