### ISSUE TITLE
Salt bridge distanced-based screeening

### ISSUE THREAD

**Issue by eneas77** [forlilab/Ringtail#7]
Hi,

Thanks for putting ringtail up :-). I´m wondering if is feasible to implement a ionic bridge type filtering scheme, similarly as hb or vdw.

Any ideas around that?

Thank you kindly.

E77

**Comment by eneas77** [comment]
Any updates around this?

Thanks

E77

**Comment by diogomart** [comment]
There's no way to do this directly, but on the develop branch there's an option called `--smarts_idxyz` that can find user-defined groups within a certain distance from a point in space. For example:
```--smarts_idxyz [CX4][N+1X4H3] 1 1.5 10.0 10.0 10.0```
Would find primary ammonium in which the nitrogen is within 1.5 Angstrom from (10.0, 10.0, 10.0).
